BASE_DIR := $(shell pwd)
BUILD_DIR := bin

all: bin/mockbroker

bin/mockbroker:
	go build -ldflags '-w -s' -o bin/mockbroker \
		github.com/openservicebrokerapi/osb-checker/mockbroker

autogenerated: autogenerated/swagger.yaml autogenerated/go-client autogenerated/go-server

autogenerated/swagger.yaml:
	wget https://raw.githubusercontent.com/openservicebrokerapi/servicebroker/master/swagger.yaml \
		-O $(BASE_DIR)/autogenerated/swagger.yaml

autogenerated/go-client:
	npx openapi-generator-cli generate \
		-i autogenerated/swagger.yaml \
		-g go \
		-o autogenerated/go-client

autogenerated/go-server:
	npx openapi-generator-cli generate \
		-i autogenerated/swagger.yaml \
		-g go-server \
		-o autogenerated/go-server \
		--additional-properties hideGenerationTimestamp=true
	rm autogenerated/go-server/go.mod

clean:
	rm -rf $(BUILD_DIR)

.PHONY: clean autogenerated/go-client autogenerated/go-server
